#!/usr/bin/env python3
"""
Query the local journal-metrics DB generated by build_journal_metrics_db.py.

Typical use:
  python scripts/query_journal_metrics.py --journal "Advanced Science"
  python scripts/query_journal_metrics.py --issn 2198-3844

Outputs JSON by default, so it can be consumed by other scripts or pasted into notes.
"""

from __future__ import annotations

import argparse
import json
import re
import sqlite3
import sys
import unicodedata
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any


def normalize_journal_name(value: str) -> str:
    value = unicodedata.normalize("NFKC", str(value)).strip().lower()
    return "".join(ch for ch in value if ch.isalnum())


def normalize_issn(value: str | None) -> str | None:
    if not value:
        return None
    text = str(value).strip().upper()
    text = re.sub(r"[^0-9X]", "", text)
    return text or None


def quartile_rank(value: str | None) -> int:
    if not value:
        return 99
    match = re.match(r"^Q([1-4])$", str(value).strip().upper())
    if not match:
        return 99
    return int(match.group(1))


@dataclass(frozen=True)
class JcrMatch:
    journal: str
    jif_2024: float | None
    quartile: str | None
    issn: str | None
    eissn: str | None
    category: str | None
    jif_rank: str | None
    partition_2023: str | None
    total_citation: int | None


@dataclass(frozen=True)
class CasMatch:
    journal: str
    partition_2025: int | None
    top: bool | None
    open_access: bool | None


def zh_yes_no_to_bool(value: Any) -> bool | None:
    if value is None:
        return None
    text = str(value).strip()
    if text == "是":
        return True
    if text == "否":
        return False
    return None


def default_db_path() -> Path:
    return Path(__file__).resolve().parents[1] / "references" / "journal_metrics_2025.sqlite3"


def fetch_all(conn: sqlite3.Connection, sql: str, params: tuple[Any, ...]) -> list[sqlite3.Row]:
    cur = conn.execute(sql, params)
    rows = cur.fetchall()
    cur.close()
    return rows


def pick_best_jcr(rows: list[sqlite3.Row]) -> sqlite3.Row | None:
    if not rows:
        return None
    return sorted(
        rows,
        key=lambda r: (
            quartile_rank(r["quartile"]),
            -(r["jif_2024"] or 0.0),
        ),
    )[0]


def pick_best_cas(rows: list[sqlite3.Row]) -> sqlite3.Row | None:
    if not rows:
        return None
    return sorted(
        rows,
        key=lambda r: (
            r["partition_2025"] if r["partition_2025"] is not None else 99,
            0 if zh_yes_no_to_bool(r["top"]) is True else 1,
        ),
    )[0]


def row_to_jcr(row: sqlite3.Row) -> JcrMatch:
    return JcrMatch(
        journal=row["journal"],
        jif_2024=row["jif_2024"],
        quartile=row["quartile"],
        issn=row["issn"],
        eissn=row["eissn"],
        category=row["category"],
        jif_rank=row["jif_rank"],
        partition_2023=row["partition_2023"],
        total_citation=row["total_citation"],
    )


def row_to_cas(row: sqlite3.Row) -> CasMatch:
    return CasMatch(
        journal=row["journal"],
        partition_2025=row["partition_2025"],
        top=zh_yes_no_to_bool(row["top"]),
        open_access=zh_yes_no_to_bool(row["open_access"]),
    )


def query_jcr(
    conn: sqlite3.Connection,
    *,
    journal_norm: str | None,
    issn_norm: str | None,
    eissn_norm: str | None,
    fuzzy: bool,
    limit: int,
) -> list[sqlite3.Row]:
    if issn_norm or eissn_norm:
        clauses = []
        params: list[Any] = []
        if issn_norm:
            clauses.append("issn_norm = ?")
            params.append(issn_norm)
        if eissn_norm:
            clauses.append("eissn_norm = ?")
            params.append(eissn_norm)
        sql = f"SELECT * FROM jcr WHERE {' OR '.join(clauses)}"
        return fetch_all(conn, sql, tuple(params))

    if not journal_norm:
        return []

    exact = fetch_all(conn, "SELECT * FROM jcr WHERE journal_norm = ?", (journal_norm,))
    if exact or not fuzzy:
        return exact

    like = f"%{journal_norm}%"
    return fetch_all(
        conn,
        "SELECT * FROM jcr WHERE journal_norm LIKE ? LIMIT ?",
        (like, limit),
    )


def query_cas(
    conn: sqlite3.Connection,
    *,
    journal_norm: str | None,
    fuzzy: bool,
    limit: int,
) -> list[sqlite3.Row]:
    if not journal_norm:
        return []

    exact = fetch_all(conn, "SELECT * FROM cas WHERE journal_norm = ?", (journal_norm,))
    if exact or not fuzzy:
        return exact

    like = f"%{journal_norm}%"
    return fetch_all(
        conn,
        "SELECT * FROM cas WHERE journal_norm LIKE ? LIMIT ?",
        (like, limit),
    )


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Query journal metrics from the local SQLite DB.")
    parser.add_argument("--db", type=Path, default=default_db_path(), help="Path to journal_metrics_2025.sqlite3")
    parser.add_argument("--journal", help="Journal name (preferred).")
    parser.add_argument("--issn", help="ISSN (hyphens optional).")
    parser.add_argument("--eissn", help="eISSN (hyphens optional).")
    parser.add_argument("--fuzzy", action="store_true", help="Enable fallback fuzzy search by name.")
    parser.add_argument("--limit", type=int, default=20, help="Limit for fuzzy results.")
    parser.add_argument("--format", choices=["json", "text"], default="json")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)

    db_path: Path = args.db
    if not db_path.is_file():
        raise SystemExit(
            f"DB not found: {db_path}. Build it first with scripts/build_journal_metrics_db.py"
        )

    journal_norm = normalize_journal_name(args.journal) if args.journal else None
    issn_norm = normalize_issn(args.issn)
    eissn_norm = normalize_issn(args.eissn)

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    try:
        jcr_rows = query_jcr(
            conn,
            journal_norm=journal_norm,
            issn_norm=issn_norm,
            eissn_norm=eissn_norm,
            fuzzy=args.fuzzy,
            limit=args.limit,
        )

        # If we have JCR hits, prefer using that normalized name to query CAS.
        cas_norm = journal_norm
        if jcr_rows:
            cas_norm = jcr_rows[0]["journal_norm"]
        cas_rows = query_cas(conn, journal_norm=cas_norm, fuzzy=args.fuzzy, limit=args.limit)

        best_jcr = pick_best_jcr(jcr_rows)
        best_cas = pick_best_cas(cas_rows)

        result = {
            "query": {
                "journal": args.journal,
                "journal_norm": journal_norm,
                "issn": args.issn,
                "issn_norm": issn_norm,
                "eissn": args.eissn,
                "eissn_norm": eissn_norm,
                "db": str(db_path),
            },
            "best": {
                "jcr": asdict(row_to_jcr(best_jcr)) if best_jcr else None,
                "cas": asdict(row_to_cas(best_cas)) if best_cas else None,
            },
            "matches": {
                "jcr": [asdict(row_to_jcr(r)) for r in jcr_rows[: args.limit]],
                "cas": [asdict(row_to_cas(r)) for r in cas_rows[: args.limit]],
            },
        }

        if args.format == "json":
            print(json.dumps(result, ensure_ascii=False, indent=2))
        else:
            print("JCR:", result["best"]["jcr"])
            print("CAS:", result["best"]["cas"])
        return 0
    finally:
        conn.close()


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
